name: app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  font_awesome_flutter: ^10.8.0
  provider: ^6.1.2
  flutter_animate: ^4.5.2
  go_router: ^14.8.1
  firebase_core: ^3.12.1  
  permission_handler: ^11.4.0
  shimmer: ^3.0.0
  flutter_chat_ui: ^1.6.15
  uuid: ^4.5.1
  http: ^1.3.0
  firebase_auth: ^5.5.1
  flutter_chat_types: ^3.6.2
  flutter_modular: ^6.3.4
  cached_network_image: ^3.4.1
  google_fonts: ^6.2.1
  camera: ^0.11.2
  cloud_firestore: ^5.6.5
  mocktail: ^1.0.4
  firebase_ai: 2.3.0
  flutter_exif_rotation: ^0.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  fake_cloud_firestore: ^3.1.0
  mockito: ^5.4.5
  build_runner: ^2.4.15
    
flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/logo_definitivo.png
    - lib/appbar/banner.png
  fonts:
    - family: Navigation
      fonts:
        - asset: fonts/Navigation.ttf
