// ignore: dangling_library_doc_comments
/// Flutter icons Navigation
/// Copyright (C) 2025 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Navigation
///      fonts:
///       - asset: fonts/Navigation.ttf
///
///
///

/// This file defines a utility class for accessing custom navigation icons.
/// The icons are generated from a custom TrueType Font (TTF) file and can be
/// used throughout the application just like standard Material or Cupertino icons.
import 'package:flutter/widgets.dart';

/// A utility class that provides static constants for custom icons.
///
/// This class is not meant to be instantiated. It serves as a namespace for
/// the icon data, making them easy to access in a structured and type-safe way.
/// For example, to use an icon, you would write: `Icon(Navigation.pokemon)`.
class Navigation {
  // This private constructor prevents anyone from instantiating this class.
  Navigation._();

  /// The font family name for the custom icon set.
  /// This must match the family name declared in pubspec.yaml.
  static const _kFontFam = 'Navigation';

  /// The package name for the font assets.
  /// This is null because the font is included directly in the application's
  /// assets, rather than being imported from a separate package.
  static const String? _kFontPkg = null;

  /// A constant that represents the 'pokemon' icon.
  /// This can be used with the `Icon` widget to display the custom icon.
  static const IconData pokemon =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
